runtime: python
env: flex
threadsafe: true
entrypoint: python -m app.app

runtime_config:
  python_version: 2

skip_files:
- .git/
- .idea/
- test/
- venv/
- pylint.log
- cloud_sql_proxy

beta_settings:
  cloud_sql_instances: uncannly:us-west2:uncannly-postgresql-instance
