def next_phoneme_probability_threshold_spectrum(potential_next_phonemes):
	total_occurrences_of_next_phonemes = sum(potential_next_phonemes.itervalues())
	stacked_phoneme_probabability_thresholds = {}
	upper_threshold_for_this_phoneme_in_range = 0.0
	for potential_next_phoneme, occurrences_of_this_phoneme in potential_next_phonemes.iteritems():
		chance_of_this_phoneme = occurrences_of_this_phoneme / total_occurrences_of_next_phonemes
		upper_threshold_for_this_phoneme_in_range += chance_of_this_phoneme
		stacked_phoneme_probabability_thresholds[potential_next_phoneme] = upper_threshold_for_this_phoneme_in_range
	return stacked_phoneme_probabability_thresholds

def simple_probabilities_of_potential_next_phonemes(potential_next_phonemes):
	total_occurrences_of_next_phonemes = sum(potential_next_phonemes.itervalues())
	simple_probability_of_each_potential_next_phoneme = {}
	for potential_next_phoneme, occurrences_of_this_phoneme in potential_next_phonemes.iteritems():
		chance_of_this_phoneme = occurrences_of_this_phoneme / total_occurrences_of_next_phonemes
		simple_probability_of_each_potential_next_phoneme[potential_next_phoneme] = chance_of_this_phoneme
	return simple_probability_of_each_potential_next_phoneme